server:
  address: 0.0.0.0
  port: 8080

# truyencv
truyencv:
    baseUri: https://truyencv.com
    titlePath: div#js-truyencv-read-content div.header h2
    contentPath: div#js-truyencv-content
    chapterPrefix: chuong-

# recive mail
kindle:
    email: lannt.xyz@kindle.com
    sender:
      username: lannt.xyz@gmail.com
      password: jtczsyijsjgisgmm
