version: "3.8"

services:
  truyencv-collector:
    image: lanntxyz/truyencv-collector:latest
    container_name: truyencv-collector
    ports:
      - '9099:8080'
    environment:
      - SPRING_CONFIG_LOCATION='/usr/app/application.yml'
    volumes:
      - ./conf/application.yml:/usr/app/application.yml
    command: ["java", "-jar", "/usr/app/truyencv-collector-0.0.1-SNAPSHOT.jar", "--spring.config.location=/usr/app/application.yml"]
